const allData = {
  current: {
    cloud: 75,
    condition: {
      code: 1003,
      icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
      text: "Partly cloudy",
    },
    dewpoint_c: 23.5,
    dewpoint_f: 74.3,
    feelslike_c: 35.6,
    feelslike_f: 96.1,
    gust_kph: 29.7,
    gust_mph: 18.5,
    heatindex_c: 33.4,
    heatindex_f: 92,
    humidity: 66,
    is_day: 0,
    last_updated: "2024-09-07 19:45",
    last_updated_epoch: 1725709500,
    precip_in: 0,
    precip_mm: 0,
    pressure_in: 29.8,
    pressure_mb: 1009,
    temp_c: 30.1,
    temp_f: 86.2,
    uv: 7,
    vis_km: 10,
    vis_miles: 6,
    wind_degree: 110,
    wind_dir: "ESE",
    wind_kph: 19.1,
    wind_mph: 11.9,
    windchill_c: 29.1,
    windchill_f: 84.4,
  },
  forecast: {
    forecastday: [
      {
        astro: {
          is_moon_up: 0,
          is_sun_up: 1,
          moon_illumination: 13,
          moon_phase: "Waxing Crescent",
          moonrise: "09:42 AM",
          moonset: "09:59 PM",
          sunrise: "06:59 AM",
          sunset: "07:06 PM",
        },
        date: "2024-09-07",
        date_epoch: 1725667200,
        day: {
          avghumidity: 76,
          avgtemp_c: 28.7,
          avgtemp_f: 83.7,
          avgvis_km: 9.5,
          avgvis_miles: 5,
          condition: [Object],
          daily_chance_of_rain: 98,
          daily_chance_of_snow: 0,
          daily_will_it_rain: 1,
          daily_will_it_snow: 0,
          maxtemp_c: 30,
          maxtemp_f: 86,
          maxwind_kph: 27,
          maxwind_mph: 16.8,
          mintemp_c: 27.6,
          mintemp_f: 81.6,
          totalprecip_in: 0.48,
          totalprecip_mm: 12.21,
          totalsnow_cm: 0,
          uv: 11,
        },
        hour: [
          [
            {
              chance_of_rain: 100,
              chance_of_snow: 0,
              cloud: 70,
              condition: {
                code: 1063,
                icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                text: "Patchy rain nearby",
              },
              dewpoint_c: 24.7,
              dewpoint_f: 76.5,
              feelslike_c: 33.2,
              feelslike_f: 91.7,
              gust_kph: 32.9,
              gust_mph: 20.4,
              heatindex_c: 33.2,
              heatindex_f: 91.7,
              humidity: 81,
              is_day: 0,
              precip_in: 0.02,
              precip_mm: 0.63,
              pressure_in: 29.83,
              pressure_mb: 1010,
              snow_cm: 0,
              temp_c: 28.3,
              temp_f: 82.9,
              time: "2024-09-07 00:00",
              time_epoch: 1725638400,
              uv: 0,
              vis_km: 9,
              vis_miles: 5,
              will_it_rain: 1,
              will_it_snow: 0,
              wind_degree: 125,
              wind_dir: "SE",
              wind_kph: 22,
              wind_mph: 13.6,
              windchill_c: 28.3,
              windchill_f: 82.9,
            },
            {
              chance_of_rain: 100,
              chance_of_snow: 0,
              cloud: 80,
              condition: {
                code: 1063,
                icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                text: "Patchy rain nearby",
              },
              dewpoint_c: 24.5,
              dewpoint_f: 76,
              feelslike_c: 32.6,
              feelslike_f: 90.7,
              gust_kph: 32.9,
              gust_mph: 20.4,
              heatindex_c: 32.6,
              heatindex_f: 90.7,
              humidity: 81,
              is_day: 0,
              precip_in: 0.01,
              precip_mm: 0.23,
              pressure_in: 29.82,
              pressure_mb: 1010,
              snow_cm: 0,
              temp_c: 28.1,
              temp_f: 82.5,
              time: "2024-09-07 01:00",
              time_epoch: 1725642000,
              uv: 0,
              vis_km: 9,
              vis_miles: 5,
              will_it_rain: 1,
              will_it_snow: 0,
              wind_degree: 128,
              wind_dir: "SE",
              wind_kph: 21.2,
              wind_mph: 13.2,
              windchill_c: 28.1,
              windchill_f: 82.5,
            },
          ],
        ],
      },
    ],
  },
  location: {
    country: "Singapore",
    lat: 1.29,
    localtime: "2024-09-07 19:50",
    localtime_epoch: 1725709847,
    lon: 103.86,
    name: "Singapore",
    region: "",
    tz_id: "Asia/Singapore",
  },
};
